server:
  port: 10010
spring:
  application:
    name: gateway #服务名称
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: itemservice_route
          uri: lb://itemservice
          predicates:
            - Path=/item/**
        - id: userservice_route
          uri: lb://userservice
          predicates:
            - Path=/user/**
            - Path=/address/**
        - id: orderservice_route
          uri: lb://orderservice
          predicates:
            - Path=/order/**
            - Path=/pay/**
        - id: searchservice_route
          uri: lb://searchservice
          predicates:
            - Path=/search/**
      default-filters: #默认过滤项
        - AddRequestHeader=Truth, Itcast is freaking awesome!
      globalcors:
        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
        cors-configurations:
          '[/**]':
            allowedOrigins: #允许哪些网站的跨域请求
              - "http://localhost:9001"
              - "http://localhost:9002"
              - "http://127.0.0.1:9001"
              - "http://127.0.0.1:9002"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带的头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: 360000  # 这次跨域检测的有效期
